### PR TITLE
Feature/landing page/navigation styling

### PR DESCRIPTION
**Pull request by cdlafortune**
Added navigation menu to the top of the page, with mobile view. 
Type
- [ ] This is a bugfix.
- [ ] This is a new feature.
- [X] This is part of a feature.
## Organization
- [X] Have you linked this pull request to a Trello card?
- [X] Have you named the branch in the format of feature/describe_feature_or_change OR bug/describe_bug_this_is_fixing
## Review
- [ ] Is this a work in progress?
- [X]  Is this ready to be reviewed?
- [X]  Have you added two reviewers to this pull request?

### CODE REVIEW

**Comment by cdlafortune** [comment]
[landing page - navigation bar with log in button](https://trello.com/c/y7IzdXY7/22-landing-page-navigation-bar-with-log-in-button)

**Review by tthompson2 — COMMENTED** [review]
All of the code related to the NavBar looks good. The code is very easy to read with a different chunks of code appropriately separated into the different files.

Did  you have to install any of packages in your dev environment to get this code to work? If not, then I'd say the code is good to merge. I was just a little bit confused about their being some sort of diff with the package-lock.json file you are pushing up and the one that was originally on the branch.

**Review by tthompson2 — APPROVED** [review]
Looks good to me. Again, really appreciate how easy it was to read.

**Review by Eloy2 — APPROVED** [review]
Great job. Well formatted and structured. Beautifully styled.

**Pull request merged**
